### ISSUE TITLE
Integration tests are broken on master

### ISSUE THREAD

**Issue by matthiasgoergens** [scroll-tech/ceno#715]
238516f652467ebb2738f7cb02052723d5d8a179 / https://github.com/scroll-tech/ceno/pull/692 seems to be the first bad commit that fails with:

```terminal
$ RUST_BACKTRACE=1 cargo run --package ceno_zkvm --example riscv_opcodes -- --start 10 --end 11
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/riscv_opcodes --start 10 --end 11`
thread 'main' panicked at ff_ext/src/lib.rs:53:13:
assertion `left == right` failed
  left: 8
 right: 2
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c94848c046d29f9a80c09aae758e27e418a289f2/library/std/src/panicking.rs:681:5
   1: core::panicking::panic_fmt
             at /rustc/c94848c046d29f9a80c09aae758e27e418a289f2/library/core/src/panicking.rs:75:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/c94848c046d29f9a80c09aae758e27e418a289f2/library/core/src/panicking.rs:364:5
   4: ff_ext::impl_goldilocks::<impl ff_ext::ExtensionField for goldilocks::structs::GoldilocksExt2>::from_bases
             at ./ff_ext/src/lib.rs:53:13
   5: <transcript::basic::BasicTranscript<E> as transcript::Transcript<E>>::read_challenge
             at ./transcript/src/basic.rs:35:17
   6: ceno_zkvm::scheme::prover::ZKVMProver<E,PCS>::create_proof
             at ./ceno_zkvm/src/scheme/prover.rs:125:13
   7: riscv_opcodes::main
             at ./ceno_zkvm/examples/riscv_opcodes.rs:304:30
   8: core::ops::function::FnOnce::call_once
             at /home/matthias/.rustup/toolchains/nightly-2024-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

_Originally posted by @matthiasgoergens in https://github.com/scroll-tech/ceno/issues/714#issuecomment-2527571873_

**Comment by matthiasgoergens** [comment]
`cargo run --package ceno_zkvm --bin e2e -- --platform=sp1 ceno_zkvm/examples/fibonacci.elf` is also broken.
